# -*- coding: utf-8 -*-
"""knn_proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l0kfHgvKatuI0JhTG3enMcu-IUwpFl_f
"""

import turicreate as tc

sf = tc.load_sframe('people12_wiki.sframe')

sf

elton = sf[sf['name'] == 'Elton John']

elton

elton['word_count'] = tc.text_analytics.count_words(elton['text'])

elton

elton_word_table = elton[['word_count']].stack('word_count',new_column_name=['word','count'])

elton_word_table

elton_word_table.sort('count',ascending=False)

sf['word_count'] = tc.text_analytics.count_words(sf['text'])

sf

sf['tfidf'] = tc.text_analytics.tf_idf(sf['word_count'])

sf

elton = sf[sf['name']=='Elton John']

elton

elton[['tfidf']].stack('tfidf',new_column_name=['word','count']).sort('count',ascending=False)

elton[['word_count']].stack('word_count',new_column_name=['word','count']).sort('count',ascending=False)

beckham = sf[sf['name']=='Victoria Beckham']

paul = sf[sf['name']=='Paul McCartney']

tc.distances.cosine(elton['tfidf'][0],beckham['tfidf'][0])

tc.distances.cosine(elton['tfidf'][0],paul['tfidf'][0])

#now building the k-nearest neighbours model

knn_model_wordCnt = tc.nearest_neighbors.create(sf,features=['word_count'],distance='cosine',label='name')

knn_model_tfidf = tc.nearest_neighbors.create(sf,features=['tfidf'],distance='cosine',label='name')

knn_model_wordCnt.query(elton)

knn_model_tfidf.query(elton)

knn_model_wordCnt.query(beckham)

knn_model_tfidf.query(beckham)

